#!/usr/bin/env sh
echo "Writing commit-id"
echo -n "<commitId>" > SIS/clarin/data/commit-id.xml
git rev-parse HEAD >> SIS/clarin/data/commit-id.xml
truncate -s-1 SIS/clarin/data/commit-id.xml
echo "</commitId>" >> SIS/clarin/data/commit-id.xml
exit 0
